[package]
name = "my_main_project"
version = "0.1.0"
authors = ["Talha-Tanveer <talhatanveer10@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
Q3 = "0.1.1"